#!/bin/sh
#%# family=auto
#%# capabilities=autoconf
if [ "$1" = "autoconf" ]; then
 if [ -n ${GETNUM} ] ; then
 echo yes
 exit 0
 else
 echo no
 exit 0
 fi
fi
if [ "$1" = "config" ]; then
 echo 'graph_title light'
 echo 'graph_args -r --lower-limit 0'
 echo 'graph_vlabel lux'
 echo 'graph_category Weather'
 echo 'balcony.label Balcony'
 echo 'balcony.min 0'
 echo 'balcony.draw LINE2'
 echo 'balcony.colour COLOUR3'
 exit 0
fi
GETNUM=`/usr/local/bin/esp8266_light.pl 13`
echo "balcony.value $GETNUM";
